#!/bin/sh
set -e
root="$(cd "$(dirname "$0")/.." && pwd)"
out="$root/src/native/confine-threaded.wasm"
build_dir="$root/native/.confine-threaded-build"
mkdir -p "$root/src/native" "$build_dir"
# A second, separate build of the same solver.c, for the worker pool that
# parallelizes solver_confine_range across threads (see confine-pool.ts).
#
# Not the main build: -sSTANDALONE_WASM refuses to combine with
# -sSHARED_MEMORY (Emscripten 4.0.21: "STANDALONE_WASM does not support
# shared memories yet"), so this drops standalone mode and imports its
# memory instead of owning it, which is what lets multiple Worker-hosted
# instances of this same module share one WebAssembly.Memory. It does NOT
# pull in Emscripten's pthread runtime (-pthread/-sUSE_PTHREADS) or its
# generated JS glue — the worker pool hand-instantiates this .wasm with its
# own ~10-line import object (confine-pool.ts), the same way solver.ts
# already hand-instantiates the standalone build. -sDECLARE_ASM_MODULE_EXPORTS=0
# keeps export names readable instead of minified to single letters, since
# nothing here is generating a matching JS glue to read minified names from.
#
# Exports only what solver_confine_range needs: the bodies array, the
# function itself, and the capacity to size views against. Everything else
# in solver.c (wires, near contacts, flocking, scent, ...) is unreachable
# from this export set and -flto strips it, so this module's static
# footprint is a sliver of the main build's — it exists only to run this one
# embarrassingly-parallel pass.
emcc "$root/native/solver.c" -O3 -msimd128 -flto \
  -sIMPORTED_MEMORY=1 -sSHARED_MEMORY=1 \
  -sDECLARE_ASM_MODULE_EXPORTS=0 \
  -sINITIAL_MEMORY=83886080 \
  -sALLOW_MEMORY_GROWTH=0 \
  -sEXPORTED_FUNCTIONS=_solver_bodies,_solver_confine_range,_solver_cap \
  -o "$build_dir/confine-threaded.js"
mv "$build_dir/confine-threaded.wasm" "$out"
rm -rf "$build_dir"
python3 - "$out" "$root/src/native/confine-threaded.b64.ts" <<'PY'
import base64, sys
from pathlib import Path
wasm, dest = Path(sys.argv[1]), Path(sys.argv[2])
b64 = base64.b64encode(wasm.read_bytes()).decode("ascii")
dest.write_text(
    "/** Generated by native/build-confine-threaded.sh. Do not edit. */\n"
    "export const CONFINE_THREADED_WASM_B64 =\n  %r;\n" % b64
)
print("wrote", dest, "(%d chars)" % len(b64))
PY
