#!/bin/sh
set -e
root="$(cd "$(dirname "$0")/.." && pwd)"
out="$root/src/native/solver.wasm"
mkdir -p "$root/src/native"
emcc "$root/native/solver.c" -O3 -msimd128 -flto --no-entry -sSTANDALONE_WASM=1 \
  -sINITIAL_MEMORY=16777216 \
  -sALLOW_MEMORY_GROWTH=0 \
  -sEXPORTED_FUNCTIONS=_solver_bodies,_solver_wires,_solver_nodes,_solver_inv_inertia,_solver_scale,_solver_kind,_solver_detailed,_solver_pair_a,_solver_pair_b,_solver_cap,_solver_wire_cap,_solver_node_cap,_solver_pair_cap,_solver_pair_count,_solver_wire_near_stride,_solver_node_stride,_solver_hits,_solver_hit_count,_solver_hit_stride,_solver_hit_cap,_solver_adj_off,_solver_adj_nei,_solver_flock_id,_solver_flock_mass,_solver_swim,_solver_adj_cap,_solver_flock,_solver_step_far,_solver_near_integrate,_solver_near_wires,_solver_near_disc,_solver_near_finalize,_solver_near_contacts,_solver_step_near,_solver_scent,_solver_scent_tmp,_solver_walls,_solver_scent_cap,_solver_wall_cap,_solver_scent_diffuse,_solver_scent_decay \
  -o "$out"
python3 - "$out" "$root/src/native/solver.b64.ts" <<'PY'
import base64, sys
from pathlib import Path
wasm, dest = Path(sys.argv[1]), Path(sys.argv[2])
b64 = base64.b64encode(wasm.read_bytes()).decode("ascii")
dest.write_text("/** Generated by native/build.sh. Do not edit. */\nexport const SOLVER_WASM_B64 =\n  %r;\n" % b64)
print("wrote", dest, "(%d chars)" % len(b64))
PY
